modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="http://www.github.com/MelanX/recipedrawer/issues/"

[[mods]]
modId="recipedrawer"
version="${file.jarVersion}"
displayName="Mod ID"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/recipedrawer.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="recipedrawer.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.recipedrawer]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipedrawer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.17)"
    ordering="NONE"
    side="BOTH"
