modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="http://www.github.com/MelanX/recipeprinter/issues/"

[[mods]]
modId="recipeprinter"
version="${file.jarVersion}"
displayName="Recipe Printer"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/recipeprinter.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="recipedrawer.png"
credits=""
authors="MelanX, noeppi_noeppi"
description='''

'''

[[dependencies.recipeprinter]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.recipeprinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.17)"
    ordering="NONE"
    side="BOTH"
